# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/database_entry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/database_entry.proto',
  package='database',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aproto/database_entry.proto\x12\x08\x64\x61tabase\"J\n\x12\x44\x61tabaseEntryProto\x12\x0c\n\x04imsi\x18\x01 \x01(\t\x12\x0f\n\x07vectors\x18\x02 \x01(\t\x12\x15\n\rmax_known_sqn\x18\x03 \x01(\tb\x06proto3')
)




_DATABASEENTRYPROTO = _descriptor.Descriptor(
  name='DatabaseEntryProto',
  full_name='database.DatabaseEntryProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imsi', full_name='database.DatabaseEntryProto.imsi', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='database.DatabaseEntryProto.vectors', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_known_sqn', full_name='database.DatabaseEntryProto.max_known_sqn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['DatabaseEntryProto'] = _DATABASEENTRYPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatabaseEntryProto = _reflection.GeneratedProtocolMessageType('DatabaseEntryProto', (_message.Message,), dict(
  DESCRIPTOR = _DATABASEENTRYPROTO,
  __module__ = 'proto.database_entry_pb2'
  # @@protoc_insertion_point(class_scope:database.DatabaseEntryProto)
  ))
_sym_db.RegisterMessage(DatabaseEntryProto)


# @@protoc_insertion_point(module_scope)
